---
title: "Getting and Cleaning Data - Course Project"
author: "Dimitris Tosios"
date: "13 November 2016"
output: html_document
---

-----------------------------
This repository contains the project for the Getting Cleaning Data Course Specialization of Data Science, Coursera.(John Hopkins University) This project is about Human Activity Recognition Using Smartophones.

###Overview
We have to make the given data set tidy. There is a lot of work to do transform a data set to a tidy data set.

###Summary
We will perform the following analysis in this project.

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

There is a description of the data variables in the COdeBook.md with all the steps and the transormations , and there is in this repository the r code for the analysis , run_analysis.R.